/** AUTOGENERATED CODE BY GHOSTGRAPH CODEGEN **/

// SPDX-License-Identifier: MIT
pragma solidity 0.8.19;

struct numberChangedEvent {
    uint256 newNumber;
}

struct numberResetEvent {
    bool numberReset;
}

struct TransferEvent {
    address from;
    address to;
    uint256 value;
}

struct ApprovalEvent {
    address owner;
    address spender;
    uint256 value;
}

struct OwnershipTransferredEvent {
    address previousOwner;
    address newOwner;
}